INSERT INTO `__prefix__Role` (`category`, `name`, `nameShort`, `description`, `type`, `canLoginRole`, `futureYearsLogin`, `pastYearsLogin`, `restriction`) VALUES
('Staff', 'Administrator', 'Adm', 'Controls all aspects of the system', 'Core', 'Y', 'Y', 'Y', 'Admin Only'),
('Staff', 'Teacher', 'Tcr', 'Regular, classroom teacher', 'Core', 'Y', 'Y', 'Y', 'None'),
('Student', 'Student', 'Std', 'Person studying in the school', 'Core', 'Y', 'Y', 'Y', 'None'),
('Parent', 'Parent', 'Prt', 'Parent or guardian of person studying in', 'Core', 'Y', 'Y', 'Y', 'None'),
('Staff', 'Support Staff', 'SSt', 'Staff who support teaching and learning', 'Core', 'Y', 'Y', 'Y', 'None');

INSERT INTO `__prefix__NotificationEvent` (`event`, `moduleName`, `actionName`, `type`, `scopes`, `active`, `module`, `action`) VALUES
('Daily Behaviour Summary', 'Behaviour', 'Find Behaviour Patterns', 'CLI', 'All', 'Y', 119, 719),
('New Negative Record', 'Behaviour', 'View Behaviour Records_all', 'Core', 'All,gibbonPersonIDStudent,gibbonYearGroupID', 'Y', 119, 608),
('New Positive Record', 'Behaviour', 'View Behaviour Records_all', 'Core', 'All,gibbonPersonIDStudent,gibbonYearGroupID', 'Y', 119, 608),
('Family Data Updates', 'Data Updater', 'Family Data Updates', 'Core', 'All', 'Y', 8, 766),
('Finance Data Updates', 'Data Updater', 'Finance Data Updates', 'Core', 'All', 'Y', 8, 775),
('Medical Form Updates', 'Data Updater', 'Medical Form Updates', 'Core', 'All', 'Y', 8, 65),
('Personal Data Updates', 'Data Updater', 'Personal Data Updates', 'Core', 'All', 'Y', 8, 63),
('Login - Failed', 'User Admin', 'Manage Users', 'Core', 'All', 'Y', 2, NULL),
('New Public Registration', 'User Admin', 'Manage Users', 'Core', 'All', 'Y', 2, NULL),
('New Application Form', 'Students', 'View Student Profile_full', 'Core', 'All', 'Y', 5, 24),
('New Application Form', 'Staff', 'Manage Applications', 'Core', 'All', 'Y', 136, 858),
('Student Withdrawn', 'Activities', 'Manage Activities', 'Core', 'All,gibbonPersonIDStudent,gibbonYearGroupID', 'Y', 15, 55),
('New Activity Registration', 'Activities', 'Manage Activities', 'Core', 'All,gibbonPersonIDStudent,gibbonYearGroupID', 'Y', 15, 55),
('Updated Individual Needs', 'Individual Needs', 'Individual Needs Records_viewEdit', 'Core', 'All,gibbonPersonIDStudent,gibbonYearGroupID', 'Y', 11, 46),
('New Student Note', 'Students', 'View Student Profile_full', 'Core', 'All,gibbonPersonIDStudent,gibbonYearGroupID', 'Y', 5, 24),
('Updated Privacy Settings', 'Students', 'View Student Profile_full', 'Core', 'All,gibbonPersonIDStudent,gibbonYearGroupID', 'Y', 5, 24),
('Daily Attendance Summary', 'Attendance', 'Roll Groups Not Registered', 'CLI', 'All', 'Y', 6, 30),
('User Status Check and Fix', 'User Admin', 'Manage Users', 'CLI', 'All', 'Y', 2, NULL),
('Behaviour Letters', 'Behaviour', 'View Behaviour Records_all', 'CLI', 'All', 'Y', 119, 608),
('Parent Weekly Email Summary', 'Planner', 'Parent Weekly Email Summary', 'CLI', 'All', 'Y', 9, 810),
('Application Form Accepted', 'Students', 'View Student Profile_full', 'Core', 'All,gibbonYearGroupID', 'Y', 5, 24),
('Weekly Attendance Summary', 'Attendance', 'Attendance Summary by Date', 'CLI', 'All,gibbonYearGroupID', 'Y', 6, 880),
('Student Bumped', 'Activities', 'Manage Activities', 'Core', 'All', 'Y', 15, 55),
('Updated Behaviour Record', 'Behaviour', 'View Behaviour Records_all', 'Core', 'All,gibbonPersonIDStudent,gibbonYearGroupID', 'Y', 119, 608);
